threads = 4          # 下载线程数
workers = 4          # 同时下载文件数
[telegram]
token = ""                                    # Bot Token
admins = [777000]                             # 你的 user_id
api_id = 123456                               # Telegram API ID
api_hash = "0123456789abcdef0123456789abcdef" # Telegram API Hash

[log]
level = "DEBUG" # 日志等级

[temp]
base_path = "cache/" # 临时目录, 请不要在此目录下存放任何其他文件
cache_ttl = 30       # 临时文件保存时间, 单位: 秒

[db]
path = "data/data.db" # 数据库文件路径

[storage]
[storage.alist] # Alist
enable = true
base_path = "/telegram"   # 保存路径
username = "admin"        # 用户名
password = "password"     # 密码
url = "https://alist.com" # Alist 地址
token_exp = 86400         # token 过期时间, 单位: 秒

[storage.local] # 本地磁盘
enable = true
base_path = "downloads/" # 保存路径

[storage.webdav] # WebDav
enable = true
base_path = "/telegram"
username = "admin"
password = "password"
url = "https://alist.com/dav"
