workers = 4 # 同时下载文件数
retry = 3   # 下载失败重试次数
threads = 4 # 单个任务下载最大线程数

[telegram]
# Bot Token
token = ""
# Telegram API 配置, 若不配置也可运行, 将使用默认的 API ID 和 API HASH
# 推荐使用自己的 API ID 和 API HASH (https://my.telegram.org)
# app_id = 123456
# app_hash = "0123456789abcdef0123456789abcdef"

[telegram.proxy]
# 启用代理连接 telegram, 只支持 socks5
enable = false
url = "socks5://127.0.0.1:7890"


# 存储配置列表
[[storages]]
# 标识名, 需要唯一
name = "本机1"
# 存储类型, 目前可用: local , alist , webdav
type = "local"
# 启用存储
enable = true
# 文件保存根路径
base_path = "./downloads"

[[storages]]
name = "本机2"
type = "local"
enable = true
base_path = "./downloads/2"

[[storages]]
name = "MyAlist"
type = "alist"
enable = false
base_path = '/'
url = 'https://alist.com'
username = 'admin'
password = 'password'
token_exp = 86400
# alist 可直接使用 token 登录, 此时 username, password, token_exp 将被忽略
# 请自行在 alist 侧配置合理的 token 过期时间
# token = ""


[[storages]]
name = "MyWebdav"
type = "webdav"
enable = false
base_path = '/path/telegram'
url = 'https://example.com/dav'
username = 'username'
password = 'password'


# 用户列表
[[users]]
# telegram user id
id = 114514
# 将过滤模式设为黑名单
blacklist = true
# 存储过滤列表
# 将列表留空并开启黑名单模式以允许使用所有存储
storages = []


[[users]]
id = 123456
blacklist = false
# 此时该用户只能使用 本机1
storages = ["本机1"]



# 其他配置

# [log]
# # 日志等级
# level = "DEBUG"

# [temp]
# # 下载文件临时目录, 请不要在此目录下存放任何其他文件
# base_path = "cache/"
# # 临时文件保存时间, 单位: 秒
# cache_ttl = 30

# [db]
# path = "data/data.db" # 数据库文件路径
