services:
  saveany-bot:
    image: ghcr.io/krau/saveany-bot:latest
    container_name: saveany-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./config.toml:/app/config.toml
      - ./downloads:/app/downloads
      - ./cache:/app/cache