baseURL = 'https://sabot.unv.app/'
title = 'Save Any Bot'
disablePathToLower = true
enableGitInfo = true
defaultContentLanguage = 'zh'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
BookTheme = 'auto'
BookToC = true
BookLogo = 'logo.png'
BookSection = '*'
BookRepo = 'https://github.com/krau/saveany-bot'
BookCommitPath = 'commit'
BookEditPath = 'edit/main/docs'

# (Optional, default January 2, 2006) Configure the date format used on the pages
# - In git information
# - In blog posts
BookDateFormat = '2006/01/02'

# (Optional, default true) Enables search function with flexsearch,
# Index is built on fly, therefore it might slowdown your website.
# Configuration for indexing can be adjusted in i18n folder per language.
BookSearch = false

[languages]

[languages.zh]
languageName = "简体中文"
contentDir = "content/zh"
weight = 1

[languages.en]
languageName = "English"
contentDir = "content/en"
weight = 2

[markup]
[markup.goldmark.renderer]
unsafe = true
